.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. nealcoin_qt test_nealcoin_qt
clean: FORCE
	$(MAKE) -C .. nealcoin_qt_clean test_nealcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_nealcoin_qt_check
nealcoin-qt nealcoin-qt.exe: FORCE
	 $(MAKE) -C .. nealcoin_qt
